### ISSUE TITLE
v0.12.0

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#241]
Okay folks,

this is the plan to release the next version!

Pull Requests to merge:
- [x] #242 Merge activities
- [x] #250 Single Note Widget
- [x] #204 Quickwin for category label
- [x] #244 Search should also include category of note 
- [x] #249 Screenshots, localized descriptions
- [x] #240 Transifex Update

Sorry, #207 Vibrate on list item move and #202 Links between notes will have to wait since there are still discussion points.

After merging those three, we will test for a while and if there no problem occurs, we will tag the version (leads to build on f-droid).
Then we will wait for a while and then release v0.12.0 on Play Store.

CC @schaarsc @dan0xii and of course @korelstar 

Thank you very much for your patience. Please solve the remaining conflicts and then let's go 🚀 !

**Comment by korelstar** [comment]
One hint: give the transifex community some time to translate new strings from merged PRs before merging #240 (Transifex Update) and tagging a new release. Otherwise, there will be many untranslated strings in the release.

**Comment by stefan-niedermann** [comment]
Okay everyone. Have i missed anything? App seems to work fine.

@dan0xii can you please give me an update of the widget state? (`master` and `dan0xii:widget_single_note_scroll2` branches - what is still on the branch, do we need it for the next release?)

Otherwise i think we can merge transifex and release.

PS.: @schaarsc and @dan0xii can you please contact me via email at info@niedermann.it? I had recently a conversation with @korelstar and have got some candy for you)

**Comment by korelstar** [comment]
I suggest to wait for #263 before releasing. I will test the current state (with #263) on my phone in the meanwhile ...

**Comment by dan0xii** [comment]
Before I saw korelstar's comment I was going to suggest leaving #263 until the next release so that 0.12.0 isn't delayed too much but if you're happy to wait then it does make the widget a lot more functional.

I've been using it on my phone since I made the PR and haven't encountered any issues.

The remaining code to merge is still needed to enable scrolling and basically sets the widget to use a listview with the single textview containing the note content as its child. I've used this to create an "all notes" widget also which I've been running on my phone. This widget has #263 as a prerequisite so I've delayed making a PR until it's merged.

**Comment by korelstar** [comment]
Good work (the ListView is a nice idea) :-)

I found no problems, so I would merge #263 and #240 and then release!

**Comment by stefan-niedermann** [comment]
Aggree, everything should be in `master` now.

I will tag tonight or tomorrow.

**Comment by stefan-niedermann** [comment]
Didn't managed it yesterday, will tag as soon as possible...
